[build]
  base = "."
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/profile"
  to = "/.netlify/functions/profile"
  status = 200
  force = true

[[redirects]]
  from = "/api/profile/*"
  to = "/.netlify/functions/profile/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
